import {
  MenubarCheckboxItem,
  MenubarCheckboxItemProps,
  MenubarContent,
  MenubarContentProps,
  MenubarGroup,
  MenubarGroupProps,
  MenubarItem,
  MenubarItemProps,
  MenubarLabel,
  MenubarLabelProps,
  MenubarMenu,
  MenubarMenuProps,
  MenubarRadioGroup,
  MenubarRadioGroupProps,
  MenubarRadioItem,
  MenubarRadioItemProps,
  MenubarRoot,
  MenubarRootProps,
  MenubarSeparator,
  MenubarSeparatorProps,
  MenubarSubMenu,
  MenubarSubMenuContent,
  MenubarSubMenuContentProps,
  MenubarSubMenuProps,
  MenubarSubMenuTrigger,
  MenubarSubMenuTriggerProps,
  MenubarTrigger,
  MenubarTriggerProps,
} from "./Menubar";

export const Menubar = {
  Root: MenubarRoot,
  Menu: MenubarMenu,
  Trigger: MenubarTrigger,
  Content: MenubarContent,
  Item: MenubarItem,
  Group: MenubarGroup,
  Label: MenubarLabel,
  CheckboxItem: MenubarCheckboxItem,
  RadioGroup: MenubarRadioGroup,
  RadioItem: MenubarRadioItem,
  Separator: MenubarSeparator,
  SubMenu: MenubarSubMenu,
  SubMenuTrigger: MenubarSubMenuTrigger,
  SubMenuContent: MenubarSubMenuContent,
};

export type {
  MenubarRootProps,
  MenubarMenuProps,
  MenubarTriggerProps,
  MenubarContentProps,
  MenubarItemProps,
  MenubarGroupProps,
  MenubarLabelProps,
  MenubarCheckboxItemProps,
  MenubarRadioGroupProps,
  MenubarRadioItemProps,
  MenubarSeparatorProps,
  MenubarSubMenuProps,
  MenubarSubMenuTriggerProps,
  MenubarSubMenuContentProps,
};
