import {
    ContextMenuRootProps,
    ContextMenuRoot,
    ContextMenuTriggerProps,
    ContextMenuTrigger,
    ContextMenuPortalProps,
    ContextMenuPortal,
    ContextMenuContentProps,
    ContextMenuContent,
    ContextMenuArrowProps,
    ContextMenuArrow,
    ContextMenuItemProps,
    ContextMenuItem,
    ContextMenuGroupProps,
    ContextMenuGroup,
    ContextMenuLabelProps,
    ContextMenuLabel,
    ContextMenuCheckboxItemProps,
    ContextMenuCheckboxItem,
    ContextMenuRadioGroupProps,
    ContextMenuRadioGroup,
    ContextMenuRadioItemProps,
    ContextMenuRadioItem,
    ContextMenuItemIndicatorProps,
    ContextMenuItemIndicator,
    ContextMenuSeparatorProps,
    ContextMenuSeparator,
    ContextMenuSubMenuProps,
    ContextMenuSubMenu,
    ContextMenuSubMenuTriggerProps,
    ContextMenuSubMenuTrigger,
    ContextMenuSubMenuContentProps,
    ContextMenuSubMenuContent,
} from './ContextMenu'

export const ContextMenu = {
    Root: ContextMenuRoot,
    Trigger: ContextMenuTrigger,
    Portal: ContextMenuPortal,
    Content: ContextMenuContent,
    Arrow: ContextMenuArrow,
    Item: ContextMenuItem,
    Group: ContextMenuGroup,
    Label: ContextMenuLabel,
    CheckboxItem: ContextMenuCheckboxItem,
    RadioGroup: ContextMenuRadioGroup,
    RadioItem: ContextMenuRadioItem,
    ItemIndicator: ContextMenuItemIndicator,
    Separator: ContextMenuSeparator,
    SubMenu: ContextMenuSubMenu,
    SubMenuTrigger: ContextMenuSubMenuTrigger,
    SubMenuContent: ContextMenuSubMenuContent,
}

export type {
    ContextMenuRootProps,
    ContextMenuTriggerProps,
    ContextMenuPortalProps,
    ContextMenuContentProps,
    ContextMenuArrowProps,
    ContextMenuItemProps,
    ContextMenuGroupProps,
    ContextMenuLabelProps,
    ContextMenuCheckboxItemProps,
    ContextMenuRadioGroupProps,
    ContextMenuRadioItemProps,
    ContextMenuItemIndicatorProps,
    ContextMenuSeparatorProps,
    ContextMenuSubMenuProps,
    ContextMenuSubMenuTriggerProps,
    ContextMenuSubMenuContentProps,
}