import {
  DropdownMenuCheckboxItem,
  DropdownMenuCheckboxItemProps,
  DropdownMenuContent,
  DropdownMenuContentProps,
  DropdownMenuGroup,
  DropdownMenuGroupProps,
  DropdownMenuItem,
  DropdownMenuItemProps,
  DropdownMenuLabel,
  DropdownMenuLabelProps,
  DropdownMenuRadioGroup,
  DropdownMenuRadioGroupProps,
  DropdownMenuRadioItem,
  DropdownMenuRadioItemProps,
  DropdownMenuRoot,
  DropdownMenuRootProps,
  DropdownMenuSeparator,
  DropdownMenuSeparatorProps,
  DropdownMenuSubMenu,
  DropdownMenuSubMenuContent,
  DropdownMenuSubMenuContentProps,
  DropdownMenuSubMenuProps,
  DropdownMenuSubMenuTrigger,
  DropdownMenuSubMenuTriggerProps,
  DropdownMenuTrigger,
  DropdownMenuTriggerProps,
} from "./DropdownMenu";

export const DropdownMenu = {
  Root: DropdownMenuRoot,
  Trigger: DropdownMenuTrigger,
  Content: DropdownMenuContent,
  Item: DropdownMenuItem,
  Group: DropdownMenuGroup,
  Label: DropdownMenuLabel,
  CheckboxItem: DropdownMenuCheckboxItem,
  RadioGroup: DropdownMenuRadioGroup,
  RadioItem: DropdownMenuRadioItem,
  Separator: DropdownMenuSeparator,
  SubMenu: DropdownMenuSubMenu,
  SubMenuTrigger: DropdownMenuSubMenuTrigger,
  SubMenuContent: DropdownMenuSubMenuContent,
};

export type {
  DropdownMenuRootProps,
  DropdownMenuTriggerProps,
  DropdownMenuContentProps,
  DropdownMenuItemProps,
  DropdownMenuGroupProps,
  DropdownMenuLabelProps,
  DropdownMenuCheckboxItemProps,
  DropdownMenuRadioGroupProps,
  DropdownMenuRadioItemProps,
  DropdownMenuSeparatorProps,
  DropdownMenuSubMenuProps,
  DropdownMenuSubMenuTriggerProps,
  DropdownMenuSubMenuContentProps,
};
